# Generated by Django 2.2 on 2024-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7qtyT9g2W_oCg8VzVYKAL81Cx--oKDeDEsA&usqp=CAU', max_length=500),
        ),
    ]
